version: 2
updates:
  - package-ecosystem: pip
    directory: /switchbot-dashboard/switchbot-backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /switchbot-dashboard
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
